---
title: "Sydney_data_cleanup"
output: html_document
date: "2025-11-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
```

Clean up MICGRA (DONE)

```{r cars}
## Read in CSV file
MICGRA1 <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/ MICGRA.csv")

## remove unuseful columns
MICGRA <- subset(MICGRA1, select = -c(S, Herbivory, X, Herbivory.1, X.1, ONotes, CNotes, Opods, Cpods))
 
## remove mono plots 
MICGRA <- subset(MICGRA, M != 0)

## turn any blooms = 0 into NAs 
MICGRA$Oblooms[MICGRA$Oblooms == 0] <- NA
MICGRA$Cblooms[MICGRA$Cblooms == 0] <- NA

## remove any NAs 
MICGRA <- MICGRA %>%
  drop_na(Oseeds, Oblooms, Cseeds, Cblooms)

## find seeds per bloom and add column 
MICGRA <- MICGRA %>%
  mutate(OSeeds_Per_bloom = round(Oseeds/Oblooms, digits = 2)) %>%
  mutate(CSeeds_Per_bloom = round(Cseeds/Cblooms, digits = 2))

## rename columns to match pollinator data
MICGRA <- MICGRA %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp)  

```

Clean up GILCAP (DONE)

```{r}
GILCAP1 <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/GILCAP.csv")

## remove unuseful columns
GILCAP <- subset(GILCAP1, select = -c(S, Herbivory, OflwrsGood, OflwrsBad, OseedsBad, OseedsGood, Omass, Herbivory.1, CflwrsGood, CflwrsBad, CseedsBad, CseedsGood, Cmass, notesOpen, notesClosed, Opods, Cpods, X))
 
## remove mono plots 
GILCAP <- subset(GILCAP, M != 0)

## turn any blooms = 0 into NAs 
GILCAP$Oblooms[GILCAP$Oblooms == 0] <- NA
GILCAP$Cblooms[GILCAP$Cblooms == 0] <- NA

## remove any NAs 
GILCAP <- GILCAP %>%
  drop_na(OseedsTotal, Oblooms, CseedsTotal, Cblooms)

## find seeds per bloom and add column 
GILCAP <- GILCAP %>%
  mutate(OSeeds_Per_bloom = round(OseedsTotal/Oblooms, digits = 2)) %>%
  mutate(CSeeds_Per_bloom = round(CseedsTotal/Cblooms, digits = 2))

## rename columns to match pollinator data
GILCAP <- GILCAP %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp)  

```

Clean up GLTCCLAAMO - Mass doesnt work?

```{r}
GLTC_CLAAMO1 <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/GLTCCLAAMO.csv")

## turn any blooms = 0 into NAs 
GLTC_CLAAMO1$Oblooms[GLTC_CLAAMO1$Oblooms == 0] <- NA
GLTC_CLAAMO1$Cblooms[GLTC_CLAAMO1$Cblooms == 0] <- NA
 ## initial drop any NA blooms 
GLTC_CLAAMO1 <- GLTC_CLAAMO1 %>%
  drop_na(Oblooms, Cblooms)
## remove mono plots 
GLTC_CLAAMO1 <- subset(GLTC_CLAAMO1, M != 0)
## remove unuseful columns
GLTC_CLAAMO <- subset(GLTC_CLAAMO1, select = -c(S, OseedsGood, OseedsBad, CseedsGood, CseedsBad, notesOpen, notesClosed))

## add key column for cleaner merge
GLTC_CLAAMO$Key <- 1:nrow(GLTC_CLAAMO)

##Linerar regression for Open seed mass:
## subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(GLTC_CLAAMO, OseedsTotal !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OseedsTotal~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]

##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(GLTC_CLAAMO, (OseedsTotal == 0 | is.na(OseedsTotal)) & Omass != 0)

## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob

##fill in empty rows 
OnoSeeds_yesMass$OseedsTotal <- Oy 

##Linerar regression for Closed seed mass:
## subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(GLTC_CLAAMO, CseedsTotal !=0 & Cmass != 0)

## linear reg:
model <- lm(CSeed_mass$CseedsTotal~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]

##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(GLTC_CLAAMO, (CseedsTotal == 0 | is.na(CseedsTotal)) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb

##fill in empty rows
CnoSeeds_yesMass$CseedsTotal <- Cy

##MAKE A FOR LOOP
CnoSeeds_yesMass$CseedsTotal <- Cy
GLTC_CLAAMO$OseedsTotal_orig <- GLTC_CLAAMO$OseedsTotal
GLTC_CLAAMO$CseedsTotal_orig <- GLTC_CLAAMO$CseedsTotal
GLTC_CLAAMO$Omass_orig <- GLTC_CLAAMO$Omass
GLTC_CLAAMO$Cmass_orig <- GLTC_CLAAMO$Cmass

## drop og columns 
GLTC_CLAAMO$OseedsTotal <- NULL
GLTC_CLAAMO$CseedsTotal <- NULL
GLTC_CLAAMO$Omass <- NULL
GLTC_CLAAMO$Cmass <- NULL

Final_GLTC_CLAAMO <- GLTC_CLAAMO

CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CseedsTotal, Key)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OseedsTotal, Key)

# Join OseedsTotal values
Final_GLTC_CLAAMO <- Final_GLTC_CLAAMO %>%
  left_join(OnoSeeds_yesMass.small, by = "Key") %>%
  mutate(OseedsTotal = ifelse(is.na(OseedsTotal), OseedsTotal.orig, OseedsTotal)) %>%
  select(-OseedsTotal.orig)
# Join CseedsTotal values
Final_GLTC_CLAAMO  <- Final_GLTC_CLAAMO %>%
  left_join(CnoSeeds_yesMass.small, by = "Key") %>%
  mutate(CseedsTotal = ifelse(is.na(CseedsTotal), CseedsTotal.orig, CseedsTotal)) %>%
  select(-CseedsTotal.orig)

## find seeds per bloom and add column 
Final_GLTC_CLAAMO <- Final_GLTC_CLAAMO %>%
  mutate(OSeeds_Per_bloom = round(OseedsTotal/Oblooms, digits = 2)) %>%
  mutate(CSeeds_Per_bloom = round(CseedsTotal/Cblooms, digits = 2))

## rename columns to match pollinator data
Final_GLTC_CLAAMO <- Final_GLTC_CLAAMO %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp)  

```

clean up GLTCCLAPUR - Need Mass

```{r}
GLTCCLAPUR1 <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/GLTCCLAPUR.csv")

## turn any blooms = 0 into NAs 
GLTCCLAPUR1$Oblooms[GLTCCLAPUR1$Oblooms == 0] <- NA
GLTCCLAPUR1$Cblooms[GLTCCLAPUR1$Cblooms == 0] <- NA
 ## initial drop any NA blooms 
GLTCCLAPUR1 <- GLTCCLAPUR1 %>%
  drop_na(Oblooms, Cblooms)
## remove mono plots 
GLTCCLAPUR1 <- subset(GLTCCLAPUR1, M != 0)
## remove unuseful columns
GLTCCLAPUR <- subset(GLTCCLAPUR1, select = -c(S, OseedsGood, OseedsBad, CseedsGood, CseedsBad, notesOpen, notesClosed, X))

##Linerar regression for Open seed mass:
## subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(GLTCCLAPUR, OseedsTotal !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OseedsTotal~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]

##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(GLTCCLAPUR, OseedsTotal == 0 | is.na(OseedsTotal) & Omass != 0)

## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob

##fill in empty rows 
OnoSeeds_yesMass$OseedsTotal <- Oy 

##Linerar regression for Closed seed mass:
## subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(GLTCCLAPUR, CseedsTotal !=0 & Cmass != 0)

## linear reg:
model <- lm(CSeed_mass$CseedsTotal~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]

##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(GLTCCLAPUR, CseedsTotal == 0 | is.na(CseedsTotal) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb

##fill in empty rows
CnoSeeds_yesMass$OseedsTotal <- Cy

##MAKE A FOR LOOP
CnoSeeds_yesMass$CseedsTotal <- Cy
Final_GLTCCLAPUR <- GLTCCLAPUR
CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CseedsTotal)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OseedsTotal)
# Join OseedsTotal values
Final_GLTCCLAPUR <- Final_GLTCCLAPUR %>%
  left_join(OnoSeeds_yesMass.small, by = "Omass", suffix = c("", ".new")) %>%
  mutate(OseedsTotal = ifelse(is.na(OseedsTotal), OseedsTotal.new, OseedsTotal)) %>%
  select(-OseedsTotal.new)
# Join CseedsTotal values
Final_GLTCCLAPUR  <- Final_GLTCCLAPUR %>%
  left_join(CnoSeeds_yesMass.small, by = "Cmass", suffix = c("", ".new")) %>%
  mutate(CseedsTotal = ifelse(is.na(CseedsTotal), CseedsTotal.new, CseedsTotal)) %>%
  select(-CseedsTotal.new)

## find seeds per bloom and add column 
Final_GLTCCLAPUR <- Final_GLTCCLAPUR %>%
  mutate(OSeeds_Per_bloom = round(OseedsTotal/Oblooms, digits = 2)) %>%
  mutate(CSeeds_Per_bloom = round(CseedsTotal/Cblooms, digits = 2))

## rename columns to match pollinator data
Final_GLTCCLAPUR <- Final_GLTCCLAPUR %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp) 

```

GLTCCOLLIGRA (DONE)

```{r}
GLTCCOLLIGRA1 <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/GLTCCOLLIGRA.csv")

## remove unuseful columns
GLTCCOLLIGRA <- subset(GLTCCOLLIGRA1, select = -c(S, OseedsGood, OseedsBad, Ocomplete., OemptyInflorMass, CseedsGood, CseedsBad, Ccomplete., CemptyInflorMass, notesOpen, notesClosed, X, X.1, X.2, X.3, X.4, X.5))
 
## remove mono plots 
GLTCCOLLIGRA <- subset(GLTCCOLLIGRA, M != 0)

## turn any blooms = 0 into NAs 
GLTCCOLLIGRA$Oblooms[GLTCCOLLIGRA$Oblooms == 0] <- NA
GLTCCOLLIGRA$Cblooms[GLTCCOLLIGRA$Cblooms == 0] <- NA

## remove any NAs 
GLTCCOLLIGRA <- GLTCCOLLIGRA %>%
  drop_na(OseedsTotal, Oblooms, CseedsTotal, Cblooms)

## find seeds per bloom and add column 
GLTCCOLLIGRA <- GLTCCOLLIGRA %>%
  mutate(OSeeds_Per_bloom = round(OseedsTotal/Oblooms, digits = 2)) %>%
  mutate(CSeeds_Per_bloom = round(CseedsTotal/Cblooms, digits = 2))

## rename columns to match pollinator data
GLTCCOLLIGRA <- GLTCCOLLIGRA %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp)  

```

