---
title: "IN data cleaning"
author: "Isabelle Nollette, Sydney James"
date: "2025-11-18"
output: html_document
---

GLTC MADGRA cleaning:
```{r}
library(dplyr)
library(tidyr)
library(tidyverse)
library(terra)
```

```{r}
GLTC_MADGRA <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/GLTCMADGRA.csv")

GLTC_MADGRA <- subset(GLTC_MADGRA, 
                      select = -c(S, lostSeeds.O, Oflorets, lostSeeds.C, Cflorets, notesOpen, notesClosed, notesOther))        

#removing mono plots
GLTC_MADGRA <- subset(GLTC_MADGRA, M != 0) 
#changing ""  and 0 to NAs 
GLTC_MADGRA[GLTC_MADGRA == ""| GLTC_MADGRA == 0] <- NA
#dropped NAs
GLTC_MADGRA <- GLTC_MADGRA %>%          
  drop_na(Oblooms, Cblooms) 

#making the headers match holiday data
GLTC_MADGRA <- GLTC_MADGRA %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp) 

#making new seeds column 
GLTC_MADGRA <- GLTC_MADGRA %>% 
  mutate(OSeeds = 
           ifelse((!is.na(OseedsGood) & OseedsGood >= 0) | (!is.na(Oseeds.Bad) & Oseeds.Bad >=0), rowSums(cbind(OseedsGood, Oseeds.Bad), na.rm = TRUE),
                  ifelse(!is.na(OseedsGood) | !is.na(Oseeds.Bad),
                         ifelse(!is.na(OseedsGood), OseedsGood, Oseeds.Bad),
                         ifelse(!is.na(OseedsTotal), OseedsTotal,
                                NA))))
GLTC_MADGRA <- GLTC_MADGRA %>% 
  mutate(CSeeds = 
           ifelse((!is.na(CseedsGood) & CseedsGood >= 0) | (!is.na(CseedsBad) & CseedsBad >=0), rowSums(cbind(CseedsGood, CseedsBad), na.rm = TRUE),
                  ifelse(!is.na(CseedsGood) | !is.na(CseedsBad),
                         ifelse(!is.na(CseedsGood), CseedsGood, CseedsBad),
                         ifelse(!is.na(CseedsTotal), CseedsTotal,
                                NA))))

#dropping old seed columns
GLTC_MADGRA <- subset(GLTC_MADGRA, 
                      select = -c(OseedsGood, Oseeds.Bad, OseedsTotal, CseedsGood, CseedsBad, CseedsTotal))
##Linear regression for seed mass:
## FOR OPEN subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(GLTC_MADGRA, OSeeds !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OSeeds~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(GLTC_MADGRA, (OSeeds == 0 | is.na(OSeeds)) & Omass != 0)
## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob
##fill in empty rows
OnoSeeds_yesMass$OSeeds <- Oy

## FOR CLOSED subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(GLTC_MADGRA, CSeeds !=0 & Cmass != 0)
## linear reg:
model <- lm(CSeed_mass$CSeeds~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(GLTC_MADGRA, (CSeeds == 0 | is.na(CSeeds)) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb
##fill in empty rows
CnoSeeds_yesMass$CSeeds <- Cy

cleaned_GLTC_MADGRA <- GLTC_MADGRA 
CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CSeeds)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OSeeds)

# Join OSeeds values
cleaned_GLTC_MADGRA <- cleaned_GLTC_MADGRA %>%
  left_join(OnoSeeds_yesMass.small, by = "Omass", suffix = c("", ".new")) %>%
  mutate(OSeeds = ifelse(is.na(OSeeds), OSeeds.new, OSeeds)) %>%
  select(-OSeeds.new)

# Join CSeeds values
cleaned_GLTC_MADGRA <- cleaned_GLTC_MADGRA %>%
  left_join(CnoSeeds_yesMass.small, by = "Cmass", suffix = c("", ".new")) %>%
  mutate(CSeeds = ifelse(is.na(CSeeds), CSeeds.new, CSeeds)) %>%
  select(-CSeeds.new)

#adding seeds per bloom 
cleaned_GLTC_MADGRA <- cleaned_GLTC_MADGRA %>%
  mutate(OSeeds_Per_Bloom = OSeeds/Oblooms,
         CSeeds_Per_Bloom = CSeeds/Cblooms)
#drop remaining NAs 
cleaned_GLTC_MADGRA <- cleaned_GLTC_MADGRA %>%
  drop_na(OSeeds, CSeeds) %>%
  subset(select = -c(Omass, Cmass))

```

WWCLAAMO cleaning: 
```{r}
WWCLAAMO <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/WWCLAAMO.csv")

WWCLAAMO <- subset(WWCLAAMO, 
                      select = -c(S, notesOpen, notesClosed))        

#removing mono plots
WWCLAAMO <- subset(WWCLAAMO, M != 0) 
#changing ""  and 0 to NAs 
WWCLAAMO[WWCLAAMO == ""| WWCLAAMO == 0] <- NA
#dropped NAs
WWCLAAMO <- WWCLAAMO %>%          
  drop_na(Oblooms, Cblooms) 

#making the headers match holiday data
WWCLAAMO <- WWCLAAMO %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp) 

#making new seeds column 
WWCLAAMO <- WWCLAAMO %>% 
  mutate(OSeeds = 
           ifelse((!is.na(OseedsGood) & OseedsGood >= 0) | (!is.na(OseedsBad) & OseedsBad >=0), rowSums(cbind(OseedsGood, OseedsBad), na.rm = TRUE),
                  ifelse(!is.na(OseedsGood) | !is.na(OseedsBad),
                         ifelse(!is.na(OseedsGood), OseedsGood, OseedsBad),
                         ifelse(!is.na(OseedsTotal), OseedsTotal,
                                NA))))
WWCLAAMO <- WWCLAAMO %>% 
  mutate(CSeeds = 
           ifelse((!is.na(CseedsGood) & CseedsGood >= 0) | (!is.na(CseedsBad) & CseedsBad >=0), rowSums(cbind(CseedsGood, CseedsBad), na.rm = TRUE),
                  ifelse(!is.na(CseedsGood) | !is.na(CseedsBad),
                         ifelse(!is.na(CseedsGood), CseedsGood, CseedsBad),
                         ifelse(!is.na(CseedsTotal), CseedsTotal,
                                NA))))

#dropping old seed columns
WWCLAAMO <- subset(WWCLAAMO, 
                      select = -c(OseedsGood, OseedsBad, OseedsTotal, CseedsGood, CseedsBad, CseedsTotal))
##Linear regression for seed mass:
## FOR OPEN subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(WWCLAAMO, OSeeds !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OSeeds~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(WWCLAAMO, OSeeds == 0 | is.na(OSeeds) & Omass != 0)
## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob
##fill in empty rows
OnoSeeds_yesMass$OSeeds <- Oy

## FOR CLOSED subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(WWCLAAMO, CSeeds !=0 & Cmass != 0)
## linear reg:
model <- lm(CSeed_mass$CSeeds~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(WWCLAAMO, CSeeds == 0 | is.na(CSeeds) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb
##fill in empty rows
CnoSeeds_yesMass$CSeeds <- Cy

cleaned_WWCLAAMO <- WWCLAAMO 
CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CSeeds)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OSeeds)

# Join OSeeds values
cleaned_WWCLAAMO <- cleaned_WWCLAAMO %>%
  left_join(OnoSeeds_yesMass.small, by = "Omass", suffix = c("", ".new")) %>%
  mutate(OSeeds = ifelse(is.na(OSeeds), OSeeds.new, OSeeds)) %>%
  select(-OSeeds.new)

# Join CSeeds values
cleaned_WWCLAAMO <- cleaned_WWCLAAMO %>%
  left_join(CnoSeeds_yesMass.small, by = "Cmass", suffix = c("", ".new")) %>%
  mutate(CSeeds = ifelse(is.na(CSeeds), CSeeds.new, CSeeds)) %>%
  select(-CSeeds.new)

#adding seeds per bloom 
cleaned_WWCLAAMO <- cleaned_WWCLAAMO %>%
  mutate(OSeeds_Per_Bloom = OSeeds/Oblooms,
         CSeeds_Per_Bloom = CSeeds/Cblooms)
#drop remaining NAs 
cleaned_WWCLAAMO <- cleaned_WWCLAAMO %>%
  drop_na(OSeeds, CSeeds) %>%
  subset(select = -c(Omass, Cmass))

```


WWCLAPUR cleaning: 
```{r}
WWCLAPUR <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/WWCLAPUR.csv")

WWCLAPUR <- subset(WWCLAPUR, 
                      select = -c(S, notes, notesClosed))        

#removing mono plots
WWCLAPUR <- subset(WWCLAPUR, M != 0) 
#changing ""  and 0 to NAs 
WWCLAPUR[WWCLAPUR == ""| WWCLAPUR == 0] <- NA
#dropped NAs
WWCLAPUR <- WWCLAPUR %>%          
  drop_na(Oblooms, Cblooms) 

#making the headers match holiday data
WWCLAPUR <- WWCLAPUR %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp) 

#making new seeds column 
WWCLAPUR <- WWCLAPUR %>% 
  mutate(OSeeds = 
           ifelse((!is.na(OseedsGood) & OseedsGood >= 0) | (!is.na(OseedsBad) & OseedsBad >=0), rowSums(cbind(OseedsGood, OseedsBad), na.rm = TRUE),
                  ifelse(!is.na(OseedsGood) | !is.na(OseedsBad),
                         ifelse(!is.na(OseedsGood), OseedsGood, OseedsBad),
                         ifelse(!is.na(OseedsTotal), OseedsTotal,
                                NA))))
WWCLAPUR <- WWCLAPUR %>% 
  mutate(CSeeds = 
           ifelse((!is.na(CseedsGood) & CseedsGood >= 0) | (!is.na(CseedsBad) & CseedsBad >=0), rowSums(cbind(CseedsGood, CseedsBad), na.rm = TRUE),
                  ifelse(!is.na(CseedsGood) | !is.na(CseedsBad),
                         ifelse(!is.na(CseedsGood), CseedsGood, CseedsBad),
                         ifelse(!is.na(CseedsTotal), CseedsTotal,
                                NA))))

#dropping old seed columns
cleaned_WWCLAPUR <- subset(WWCLAPUR, 
                      select = -c(OseedsGood, OseedsBad, OseedsTotal, CseedsGood, CseedsBad, CseedsTotal))

#adding seeds per bloom 
cleaned_WWCLAPUR <- cleaned_WWCLAPUR %>%
  mutate(OSeeds_Per_Bloom = OSeeds/Oblooms,
         CSeeds_Per_Bloom = CSeeds/Cblooms)
#drop remaining NAs 
cleaned_WWCLAPUR <- cleaned_WWCLAPUR %>%
  drop_na(OSeeds, CSeeds) %>%
  subset(select = -c(Omass, Cmass))
```


WWCOLLIGRA cleaning: 
```{r}
WWCOLLIGRA <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/WWCOLLIGRA.csv")

WWCOLLIGRA <- subset(WWCOLLIGRA, 
                      select = -c(S, Ocomplete., Ccomplete., notesOpen, notesClosed, 19,20,21,22,23,24))  #remove unuseful columns

#removing mono plots
WWCOLLIGRA <- subset(WWCOLLIGRA, M != 0) 
#changing ""  and 0 to NAs 
WWCOLLIGRA[WWCOLLIGRA == ""| WWCOLLIGRA == 0] <- NA
#dropped NAs
WWCOLLIGRA <- WWCOLLIGRA %>%          
  drop_na(Oblooms, Cblooms) 

#making the headers match holiday data
WWCOLLIGRA <- WWCOLLIGRA %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp, 
         "Omass" = OemptyInflorMass, 
         "Cmass" = CemptyInflorMass) 

#making new seeds column 
WWCOLLIGRA <- WWCOLLIGRA %>% 
  mutate(OSeeds = 
           ifelse((!is.na(OseedsGood) & OseedsGood >= 0) | (!is.na(OseedsBad) & OseedsBad >=0), rowSums(cbind(OseedsGood, OseedsBad), na.rm = TRUE),
                  ifelse(!is.na(OseedsGood) | !is.na(OseedsBad),
                         ifelse(!is.na(OseedsGood), OseedsGood, OseedsBad),
                                NA)))
WWCOLLIGRA <- WWCOLLIGRA %>% 
  mutate(CSeeds = 
           ifelse((!is.na(CseedsGood) & CseedsGood >= 0) | (!is.na(CseedsBad) & CseedsBad >=0), rowSums(cbind(CseedsGood, CseedsBad), na.rm = TRUE),
                  ifelse(!is.na(CseedsGood) | !is.na(CseedsBad),
                         ifelse(!is.na(CseedsGood), CseedsGood, CseedsBad),
                                NA)))

#dropping old seed columns
WWCOLLIGRA <- subset(WWCOLLIGRA, 
                      select = -c(OseedsGood, OseedsBad, CseedsGood, CseedsBad))
##Linear regression for seed mass:
## FOR OPEN subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(WWCOLLIGRA, OSeeds !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OSeeds~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(WWCOLLIGRA, OSeeds == 0 | is.na(OSeeds) & Omass != 0)
## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob
##fill in empty rows
OnoSeeds_yesMass$OSeeds <- Oy

## FOR CLOSED subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(WWCOLLIGRA, CSeeds !=0 & Cmass != 0)
## linear reg:
model <- lm(CSeed_mass$CSeeds~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(WWCOLLIGRA, CSeeds == 0 | is.na(CSeeds) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb
##fill in empty rows
CnoSeeds_yesMass$CSeeds <- Cy

cleaned_WWCOLLIGRA <- WWCOLLIGRA 
CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CSeeds)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OSeeds)

# Join OSeeds values
cleaned_WWCOLLIGRA <- cleaned_WWCOLLIGRA %>%
  left_join(OnoSeeds_yesMass.small, by = "Omass", suffix = c("", ".new")) %>%
  mutate(OSeeds = ifelse(is.na(OSeeds), OSeeds.new, OSeeds)) %>%
  select(-OSeeds.new)

# Join CSeeds values
cleaned_WWCOLLIGRA <- cleaned_WWCOLLIGRA %>%
  left_join(CnoSeeds_yesMass.small, by = "Cmass", suffix = c("", ".new")) %>%
  mutate(CSeeds = ifelse(is.na(CSeeds), CSeeds.new, CSeeds)) %>%
  select(-CSeeds.new)

#adding seeds per bloom 
cleaned_WWCOLLIGRA <- cleaned_WWCOLLIGRA %>%
  mutate(OSeeds_Per_Bloom = OSeeds/Oblooms,
         CSeeds_Per_Bloom = CSeeds/Cblooms)
#drop remaining NAs 
cleaned_WWCOLLIGRA <- cleaned_WWCOLLIGRA %>%
  drop_na(OSeeds, CSeeds) %>%
  subset(select = -c(Omass, Cmass))
```

WWMADGRA
```{r}
WWMADGRA <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/WWMADGRA.csv")

WWMADGRA <- subset(WWMADGRA, M != 0)       #removing mono plots

WWMADGRA <- WWMADGRA %>%
  rename("Stand" = St, 
          "Seed_Mix" = M,
          "Treatment" = genSpec,
          "PlantGenusSpecies" = Sp)   #making the headers correct

#making new seeds column 
WWMADGRA <- WWMADGRA %>% 
  mutate(OSeeds = 
           ifelse((!is.na(OseedsGood) & OseedsGood >= 0) | (!is.na(Oseeds.Bad) & Oseeds.Bad >=0), rowSums(cbind(OseedsGood, Oseeds.Bad), na.rm = TRUE),
                  ifelse(!is.na(OseedsGood) | !is.na(Oseeds.Bad),
                         ifelse(!is.na(OseedsGood), OseedsGood, Oseeds.Bad),
                                NA)))
WWMADGRA <- WWMADGRA %>% 
  mutate(CSeeds = 
           ifelse((!is.na(CseedsGood) & CseedsGood >= 0) | (!is.na(CseedsBad) & CseedsBad >=0), rowSums(cbind(CseedsGood, CseedsBad), na.rm = TRUE),
                  ifelse(!is.na(CseedsGood) | !is.na(CseedsBad),
                         ifelse(!is.na(CseedsGood), CseedsGood, CseedsBad),
                                NA)))

#dropping old seed columns
WWMADGRA <- subset(WWMADGRA, 
                      select = -c(OseedsGood, Oseeds.Bad, CseedsGood, CseedsBad))
##Linear regression for seed mass:
## FOR OPEN subset for data rows that have both total seeds and mass:
OSeed_mass <- subset(WWMADGRA, OSeeds !=0 & Omass != 0)
## linear reg:
model <- lm(OSeed_mass$OSeeds~OSeed_mass$Omass)
Ob <- model$coefficients[1]
Om <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
OnoSeeds_yesMass <- subset(WWMADGRA, OSeeds == 0 | is.na(OSeeds) & Omass != 0)
## get the mass column for the regression
Ox <- OnoSeeds_yesMass$Omass
Oy <- Om*Ox+Ob
##fill in empty rows
OnoSeeds_yesMass$OSeeds <- Oy

## FOR CLOSED subset for data rows that have both total seeds and mass:
CSeed_mass <- subset(WWMADGRA, CSeeds !=0 & Cmass != 0)
## linear reg:
model <- lm(CSeed_mass$CSeeds~CSeed_mass$Cmass)
Cb <- model$coefficients[1]
Cm <- model$coefficients[2]
##subset data to get rows that have mass but dont have seeds
CnoSeeds_yesMass <- subset(WWMADGRA, CSeeds == 0 | is.na(CSeeds) & Cmass != 0)
## get the mass column for the regression
Cx <- CnoSeeds_yesMass$Cmass
Cy <- Cm*Cx+Cb
##fill in empty rows
CnoSeeds_yesMass$CSeeds <- Cy

cleaned_WWMADGRA <- WWMADGRA 
CnoSeeds_yesMass.small <- CnoSeeds_yesMass %>% select(Cmass, CSeeds)
OnoSeeds_yesMass.small <- OnoSeeds_yesMass %>% select(Omass, OSeeds)

# Join OSeeds values
cleaned_WWMADGRA <- cleaned_WWMADGRA %>%
  left_join(OnoSeeds_yesMass.small, by = "Omass", suffix = c("", ".new")) %>%
  mutate(OSeeds = ifelse(is.na(OSeeds), OSeeds.new, OSeeds)) %>%
  select(-OSeeds.new)

# Join CSeeds values
cleaned_WWMADGRA <- cleaned_WWMADGRA %>%
  left_join(CnoSeeds_yesMass.small, by = "Cmass", suffix = c("", ".new")) %>%
  mutate(CSeeds = ifelse(is.na(CSeeds), CSeeds.new, CSeeds)) %>%
  select(-CSeeds.new)

#adding seeds per bloom 
cleaned_WWMADGRA <- cleaned_WWMADGRA %>%
  mutate(OSeeds_Per_Bloom = OSeeds/Oblooms,
         CSeeds_Per_Bloom = CSeeds/Cblooms)
#drop remaining NAs 
cleaned_WWMADGRA <- cleaned_WWMADGRA %>%
  drop_na(OSeeds, CSeeds) %>%
  subset(select = -c(Omass, Cmass))
```