---
title: "Analysis Joined"
output: html_document
date: "2025-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("bipartite")
```


 Cleaning and joining pollinator data 
 
```{r cars}
library(bipartite)
library(dplyr)
library(tidyr)
library(tibble)
veg <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/veg.csv")
ints <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/Holiday_PP_Interaction.csv")
#veg <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/veg.csv")
#ints <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/Holiday_PP_Interaction.csv")

veg_data <- veg %>%
  separate(col = Stand, into = c("Stand", "Loc"), sep = ":") %>%
  subset(Stand = c("604","605","607","611","700","702","704","705")) %>%
  subset(Site == 6) %>%
  subset(Transect != "Unenhanced") %>%
  subset(select = c("Stand", "Date", "Transect", "PlantGenusSpecies"))

ints1 <- ints %>%
  filter(Year == 2024) %>%
  separate(col = Stand, into = c("Year1", "Stand"), sep = "_") %>%
  separate(col = Stand, into = c("Stand", "Site"), sep = ":") %>%
  filter(Stand == "604" | Stand == "605" | Stand == "607" | Stand == "611" | Stand == "700" | Stand ==     "702" | Stand == "704" | Stand == "705")

both_data1 <- ints1 %>%
  inner_join(veg_data, by = "Stand", relationship = "many-to-many") %>%
  subset(select = -c(X, Year1, Site, Year, DoyStart)) %>%
  rename("Pollinator" = GenusSpecies, "Plant" = PlantGenusSpecies.y) 


#Remove extra plant data 
both_data1$PlantGenusSpecies.x <- NULL
#merge stand and sampling round 
both_data1$Standsr <- paste(both_data1$Stand, both_data1$Transect, both_data1$Date, sep = "_")

#Split all data into each stand
Stand_df <- split(both_data1, both_data1$Standsr, drop = FALSE)

# collect all Plants and Pollinator names: 
all_plants <- unique(unlist(lapply(Stand_df, function(df) df$Plant)))
all_pollinators <- unique(unlist(lapply(Stand_df, function(df) df$Pollinator)))

# Make each community into adjacency matrix stored in a list - for loop retaining no of rows/col

WHOLE_LIST <- vector("list", length = length(Stand_df))
for(i in seq_along(Stand_df)){
 ThisMix <- Stand_df[[i]] %>%
  ungroup() %>%
  complete(Plant = all_plants, Pollinator = all_pollinators, fill = list(interactions = 0)) %>%
  group_by(Pollinator, Plant) %>%
  summarize(interactions = n(), .groups = "drop") %>%
  pivot_wider(names_from = Pollinator, values_from = interactions, values_fill = 0) %>%
  column_to_rownames( var = "Plant")
  ThisMix[is.na(ThisMix)] <- 0
  ThisMix[ThisMix == 1] <- 0
  WHOLE_LIST[[i]] <- ThisMix
  names(WHOLE_LIST) <- names(Stand_df)
}

nested_values <- vector(length = length(WHOLE_LIST))
for(i in seq_along(WHOLE_LIST)){
  this.mat <- as.matrix(WHOLE_LIST[[i]])
  empty(this.mat, count = FALSE)
  rownames(this.mat) <- rownames(WHOLE_LIST[[i]])
  nodf <- networklevel(this.mat, index = "NODF")
  nested_values[[i]] <- round(nodf, digits = 3)
}

nested_values_st <- paste(names(WHOLE_LIST), nested_values, sep = "_")
head(nested_values_st)

```
Prepare Seed data to be joined to nestedness values:


Create null model: 

``` {r}

set.seed(1)
# vegan's oecosimu framework with quasiswap (fixed row & column sums)
null_fun <- function(x) vegan::nestedtemp(x, index = "NODF", weighted = TRUE)$statistic

standnull_nested_values <- lapply(WHOLE_LIST, function(nullmodel) {
  oecosimu(nullmodel, null_fun, method = "r2dtable", nsimul = 100)
})
names(standnull_nested_values) = names(WHOLE_LIST)

nested_vec <- sapply(standnull_nested_values, function(x) unname(x$statistic))
nestedness_values_df <- tibble(
  name = names(nested_vec),
  null_nestedness = unlist(nested_vec)
) %>%
  separate(name, into = c("stand", "mix", "date"), sep = "_", remove = TRUE)

#creating a heat map of all communities 

#  long_WHOLE_LIST <- map_df(names(WHOLE_LIST), function(Stand_Mix) {
#   map_mat <- WHOLE_LIST[[Stand_Mix]]
#   as.data.frame(map_mat) %>%
#     mutate(Plant = rownames(map_mat)) %>%
#     pivot_longer(
#       cols = -Plant,
#       names_to = "Pollinator",
#       values_to = "Interactions"
#     ) %>%
#     mutate(Network = Stand_Mix)
# })
#  
# long_WHOLE_LIST <- long_WHOLE_LIST %>%
#   mutate(Network = factor(Network, levels = names(WHOLE_LIST)))
# 
# long_WHOLE_LIST <- long_WHOLE_LIST %>%
#   unite("Network_Plant", Network, Plant, sep = " | ", remove = FALSE)

# ggplot(long_WHOLE_LIST, aes(x = Pollinator, y = Network_Plant, fill = Interactions)) +
#   geom_tile() +
#   scale_fill_gradient(low = "springgreen", high = "springgreen4") +
#   theme_minimal() +
#   labs(
#     x = "Pollinator",
#     y = "Network | Plant",
#     title = "All Plant–Pollinator Networks Combined Into One Heat Map"
#   ) +
#   theme(
#     axis.text.x = element_text(angle = 45, hjust = 1),
#     axis.text.y = element_text(size = 7)
#   )
```

prepare seed data 

```{r}
seed_count <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/All_Cleaned_Data")

# rename mixes to match pollinator/data
seed_count$Seed_Mix <- as.character(seed_count$Seed_Mix)
seed_count$Seed_Mix[seed_count$Seed_Mix == 1] <- "Mix1"
seed_count$Seed_Mix[seed_count$Seed_Mix == 2] <- "Mix2"
seed_count$Seed_Mix[seed_count$Seed_Mix == 3] <- "Mix3"
seed_count$Seed_Mix[seed_count$Seed_Mix == 4] <- "Mix4"
seed_count$Seed_Mix[seed_count$Seed_Mix == 5] <- "Mix5"
seed_count$Seed_Mix[seed_count$Seed_Mix == 6] <- "Mix6"

# rename plants to match pollinator/data
seed_count$PlantGenusSpecies[seed_count$PlantGenusSpecies == "CLAAMO"] <- "Clarkia amoena" seed_count$PlantGenusSpecies[seed_count$PlantGenusSpecies ==　"CLAPUR" ] <- "Clarkia purpurea"
seed_count$PlantGenusSpecies[seed_count$PlantGenusSpecies == "GILCAP"] <- "Gilia capitata"
seed_count$PlantGenusSpecies[seed_count$PlantGenusSpecies == "COLLIGRA"] <- "Collinsia grandiflora"
seed_count$PlantGenusSpecies[seed_count$PlantGenusSpecies == "MADGRA"] <- "Madia gracilis"
  
  
# rename columns and remove uneeded ones
seed_count1 <- seed_count %>%
  rename("Transect" = Seed_Mix, "Plant" = PlantGenusSpecies) %>%
  subset(select = -c(X, Treatment)) %>%
  filter(Plant != "MICGRA")

# paste stand and mix and split seed data by these combos 
seed_count1$Standsr1 <- paste(seed_count1$Stand, seed_count1$Transect, sep = "_")
seed_count_open <- seed_count1 %>%
  group_by(Standsr1) %>%
  summarise(av_OSeeds_Per_Bloom = mean(OSeeds_Per_Bloom))

seed_count_closed <- seed_count1 %>%
  group_by(Standsr1) %>%
  summarise(av_CSeeds_Per_Bloom = mean(CSeeds_Per_Bloom))


```

Join null and actual nestedness

```{r}
# separtate vector into unique stand and mix and create data frame then 
df_nested <- tibble(
  name = nested_values_st) %>%
  separate(name, into = c("stand", "mix", "date", "nestedness"), sep = "_", remove = TRUE)
  
# join null to actual 
df_all <- df_nested %>%
inner_join(nestedness_values_df)

# find average for every stand and mix combo by averaging nestedness of different dates
nestedness_av_final <- df_all %>%
  group_by(stand, mix) %>%
  mutate(nestedness = as.numeric(nestedness)) %>%
  summarise(
    av_nestedness_actual = mean(nestedness, na.rm = TRUE), 
    av_nestedness_null = mean(null_nestedness))

nestedness_av_final$Standsr1 <- paste(nestedness_av_final$stand, nestedness_av_final$mix, sep = "_")
nestedness_av_final$stand <- NULL
nestedness_av_final$mix <- NULL

nestedness_av_final <- nestedness_av_final %>%
  filter(Standsr1 != "605_Mix2") # this row was ommitted in the seed data and thus is extra

write.csv(nestedness_av_final, "nestedness_av_final.csv", row.names = FALSE)

```

```

