---
title: "Visualisations_Final"
output: html_document
date: "2025-12-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.package(igraph)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(igraph)

```

Create Network visualization 

```{r}
# Manipulate whole list to have only 47 communities like the other dfs

WHOLE_LIST_vis <- 

  # Convert to igraph bipartite adjacency matrix for every community, find modules

network_BA_matrix <- vector("list", length = length(WHOLE_LIST_vis))
for(i in seq_along(WHOLE_LIST_vis)){
  network.mat <- as.matrix(WHOLE_LIST_vis[[i]])
  empty(network.mat, count = FALSE)
  rownames(network.mat) <- rownames(WHOLE_LIST_vis[[i]])
  network_BA_matrix[[i]] <- graph_from_biadjacency_matrix(network.mat,
                                           weighted =TRUE) 
  modules[[i]] <- cluster_walktrap(network_BA_matrix[[i]]) # find modules
  groups[[i]] <- membership(modules[[i]]) # assign vertices to modules
  network_net3d <- igraph_to_networkD3(network_BA_matrix[[i]], groups[[i]]=groups[[i]], 
                                       what = "both") # convert to a network 3d object

  # ### find modules
# mod_osmia <- cluster_walktrap(g_osmia)
# ### assign vertices to modules
# groups <- membership(mod_osmia)
# 
# ### convert to a network 3d object
# g_osmia_net3d <- igraph_to_networkD3(g_osmia, group=groups, 
#                                        what = "both")
# ### plot the osmia-plant network
# forceNetwork(Links = g_osmia_net3d$links,
#              Nodes = g_osmia_net3d$nodes,
#             Source = "source", Target = "target",
#             Value = "value",  NodeID = "name",
#              Group = "group", 
#             opacity = 0.8, zoom=TRUE, opacityNoHover = 0.9)
# 
# sankeyNetwork(Links = g_osmia_net3d$links,
#              Nodes = g_osmia_net3d$nodes,
#             Source = "source", Target = "target",
#             Value = "value",  NodeID = "name", 
#             nodePadding = 0, height = 5000)
  
#WHOLE_LIST <- readRDS("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/WHOLE_LIST.rds")
WHOLE_LIST <- readRDS("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/WHOLE_LIST.rds")
  
agg_by_mix <- lapply(split(WHOLE_LIST, your_mix_vector), function(sublist) {
  Reduce("+", sublist)   # add adjacency matrices together
})

```


Create scatter/line plot to show seed vs nestedness 

```{r}
#final_data <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/final_df")
final_data <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/final_df")


final_data2 <- final_data %>%
  separate(Standsr1, into = c("Stand", "Mix"), sep = "_") %>%
  group_by(Mix) %>%
  mutate(
    PollinationBenefit = av_OSeeds_Per_Bloom - av_CSeeds_Per_Bloom
  )

lm_POLLINATORBENEFITvNESTEDNESS <- lm(PollinationBenefit ~ av_nestedness_null * Mix, data = final_data2)
summary(lm_POLLINATORBENEFITvNESTEDNESS)
anova(lm_POLLINATORBENEFITvNESTEDNESS)

ggplot(final_data2, aes(x = av_nestedness_null, y = PollinationBenefit, color = Mix)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  theme_bw() +
  labs(
    title = "Relationship Between Nestedness and Seed Set",
    x = "Standardized Nestedness",
    y = "Seed Set"
  )
ggsave("nestednessVseedset_bymix.png", width = 6, height = 4, dpi = 300)

#final_dfMIX <- read.csv("/Users/isabellenollette/Desktop/final_community_assembly-SJIN/data/final_dfMIX.csv")
final_dfMIX <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/final_community_assembly-SJIN/data/final_dfMIX.csv")

final_dfMIX <- final_dfMIX %>%
  mutate(
    PollinationBenefit = av_OSeeds_Per_Bloom - av_CSeeds_Per_Bloom,
    Mix = mix
  )

ggplot(final_dfMIX, aes(x = av_nestedness_null, y = PollinationBenefit, color = Mix)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  theme_bw() +
  labs(
    title = "Nestedness vs Seed Set Averaged by Mix",
    x = "Standardized Nestedness",
    y = "Seed Set"
  )
ggsave("nestednessVseedset.png", width = 6, height = 4, dpi = 300)

# just plot mix 4 and 5 (highest and lowest nestedness)

final_dfMIX_edit <- final_dfMIX %>%
  mutate(
    PollinationBenefit = av_OSeeds_Per_Bloom - av_CSeeds_Per_Bloom,
    Mix = mix
  ) %>%
  filter(mix == "Mix4" | mix == "Mix5" | mix == "Mix1" | mix == "Mix2")

ggplot(final_dfMIX_edit, aes(x = av_nestedness_null, y = PollinationBenefit, color = Mix)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  theme_bw() +
  labs(
    title = "Nestedness vs Seed Set",
    x = "Standardized Nestedness",
    y = "Seed Set"
  )
ggsave("nestednessVseedset_bymix.png", width = 6, height = 4, dpi = 300)

```

