---
title: 'Effective pollinators in community assembly: Literature Review'
author: "Isabelle Nollette, Sydney James"
date: "2025-11-05"
output: html_document
bibliography: references.bib
link-citation: true
---
```{r}
```

# What community assemblages result in the greatest amount of nestedness and how does this impact reproductive success?

## Problem & significance (big‑picture reviews)
We understand that plant-pollinator interactions are a key driver of community assembly and species establishment in any ecosystem. Thus, knowing which of these interactions will promote positive species coexistence by enhancing reproductive success is critical to ensuring population persistence in the face of an ever-changing environment (@moeller_pollinator_2005) . 
The dynamics of these plant-pollinator interactions have been explored as a driver of species richness (@memtsas_what_2022), where the objective is often community resilience to an external stressor. Such reliance is usually related to the structure of specialists and generalists of both plants and pollinators within a community. Abundance of generalist pollinators is often high (@moeller_pollinator_2005) and advances the transfer of pollen between plants; however, some degree of specialisation is necessary for successful pollination for flowers requiring conspecific pollen (@brosi_pollinator_2016). This structure is usually defined as the level of nestedness - the tendency for specialists to interact with subsets of the species that generalists interact with. It is thought that a perfectly nested community is the most resilient (@brosi_pollinator_2016). 
Highly specialised systems like the fiscus trees and their wasp pollinators experience a trade-off between high reproductive success and low resilience, therefore experiencing a low level of nestedness. Thus, our analysis will investigate reproductive success as an output of nestedness to grow an understanding of how the trade-off between resilience and reproductive success can promote community population persistence in different community assemblies. 



## Past work & data landscape (who/where/how; gaps)
Existing literature in the field of community assembly has focused on how direct interactions among plants (e.g. competition for resources) and abiotic factors (e.g. soil moisture) influence their persistence in a particular habitat (@sargent_plantpollinator_2008). Moreover, studies predicting how community and species characteristics such as niche overlaps, specialisation, trait divergence and distribution, and phylogenetics influence patterns of species co-occurrence and persistence within a community are not uncommon (@moeller_pollinator_2005, @ponisio_opportunistic_2017, @sargent_plantpollinator_2008, @slingsby_phylogenetic_2006, J.A.). 
However, this research has little consideration for the role of plant-animal interactions in the greater community context, particularly that of the local pollinator networks as a potential habitat filter and driver of plant fitness. Instead, focus is often on the scale of direct plant-animal interactions. 

Through deeper analysis of this existing literature, we can gain an understanding of current plant-pollinator network dynamics, where specialist pollinators are often found in greater abundance yet with lower diversity, and the inverse is true for generalist (@moeller_pollinator_2005). These dynamics can also be understood as a metric of nestedness, which encompasses the specialisation of plants and pollinators as a vector of species richness, and therefore can add to our understanding of the drivers behind reproductive success in these plant-pollinator networks. Additionally, we know that plant species with similar flowering phenologies and floral morphologies may compete for pollination, consequently making pollinator effectiveness and occurrence a driver of reproductive success in communities with congeners (@bell_interspecific_2005). There is also a wealth of research that outlines the two potential mechanisms of competition for pollination, as pollinator preference and improper pollen transfer, where the latter occurs when heterospecific pollen is deposited on stigmas of one or both competitors. Both of these mechanisms are important factors in plant-pollinator networks as they can be confounding on reproductive success, and limit the extent to which congeners can beneficially coexist (@bell_interspecific_2005).

Surveys of floral visitor communities across large geographic ranges to examine the network of pollinators and their contribution to community assembly are frequent and provide a strong framework for the methods of this study. Differently, the data for this project allows for the examination of pollination effectiveness at a smaller spatial scale, and focuses analysis in communities native to a defined ecoregion to enhance targeted restoration efforts. 


## Purpose & why now

Wetland prairies are a critical part of the Oregon ecosystem. Wetland prairies are biodiversity hotspots that improve water quality, recharge groundwater, reduce flood severity, and support breeding and migrating wildlife. However, almost all remaining Willamette Valley prairies have been degraded by human pollution, invasive species, and altered water regimes. Thus, the need for restoration is unquestionably important. The role of pollinators is critical to the reproductive success of plant communities, and has delicate margins in doing so. Thus, research using data collected in the Willamette Valley such as this project can strengthen existing knowledge on community assembly and pollinator community composition, better informing specific restoration efforts such as the Oregon Conservation Strategy, to prioritize the most productive community assemblages. By visualizing reproductive success as it relates to the structure of the plant-pollinator interactions, this study will strengthen existing knowledge about ecosystem productivity, and provide evidence to help restore degraded landscapes. Creating a nestedness model for different community assemblies will help support a statistical analysis of resilience and uphold the purpose of the study. 

### Hypotheses (directional) & brief rationale
Understanding research done by @moeller_pollinator_2005 and @brosi_pollinator_2016 on the structure of specialisation in pollinator communities visiting Clarkia plants across a wide geographic range is fundamental to the formation of our hypothesis. Building upon the understanding that the difference in pollinator communities between plant communities is due to the proportion of specialists versus generalists, rather than diversity, we form our first hypothesis:
We predict that Clarkia reproductive success will be greater in communities with less floral overlap and a more specialised pollinator community structure, due to reduced pollen interference and resource competition. These communities are predicted to be the least nested.
Conversely, we predict that communities with more congeners to Clarkia will attract greater overall abundance of pollinators; however, reproductive success and pollinator biodiversity will be lower. These communities are predicted to be the most nested.
Therefore, the optimal, most nested plant assemblage for restoration will feature limited plant overlap but high pollinator sharing.


## Dataset identification
Our first data set was collected by the Hallett Lab at the University of Oregon for Jasmin Albert’s graduate research on community coexistence. Data was collected at the Hallett Lab’s Holiday Farm site in the Willamette Valley, Oregon, an area that experienced fire in 2020. Data were collected from sites and plots each year from 2021 to 2024, which were seeded with varying mixes of generalists and specialists. 
At each plot wihtin each stand, one 2mx2m plot was watched for 10 minutes, and a pollinator was collected when it touched the reproductive part of the flower. 

Our plan is to meet with Rose and Jasmin on Monday the 17th to gain further understanding of the data which will then inform our workflow plan as we begin manipulating the data. 

## Workflow plan (prose)
1) Cleaning & validation:
First, the stand, plot, and year columns will be separated into individual columns so they can be easily subsetted and sorted. Next, we will subset or filter the data to only 2024 include observations from 2024. Focusing on 2024 allows us to control for, and isolate influences such as post-fire recovery patterns and ensures our analysis of the relationship between nestedness and reproductive success draws from the year with the most complete data. All 0 values will be kept unless meta data in the csv file contains collections notes that suggests the data point be removed.
2) Aggregations/derivations:
The plant and pollinator data will be put into a matrix, and then multiplied by a vector containing the treatment(seed mix), sampling round and stand. This will result in a list of matrices, which each item on the list representing a unique combination of seed mix, stand, and plant-pollinator interaction. 
3) Functions/loops (inputs → outputs): 
We will then write a for loop that applies the networklevel function to each matrix in the list, using index = “NODF” to compute nestedness for each plant in each stand in each treatment. This for loop will fill and empty data frame. 
We will then create a null model to compare these values by randomising community structure (treatment) and running multiple iterations of the same loop on the randomised matricies. 
4) Statistical test + programmatic implementation:
We will create a regression comparing the seed set to NODF (nestedness) of both our null model and our observed, and compare the two to find our p-value, which will indicate if we accept or reject our null hypothesis. We will also find the z-score of our null models and compare those to the z-scores of our observed data to gain an understanding of significant variation within the data. 
5) Planned visualisations/tables: 
We will generate a nestedness model for each community (seed mix) to complement the statistical and numerical results. Additionally, histograms of pollinator species abundance may be beneficial to illustrate pollinator biodiversity separate from the specialized structure of the network. Finally, a 3D network visualization could be produced to illustrate the nestedness with node size defined by seed set.
6) Risks & mitigations:
Potential risks include unmeasured biotic or abiotic factors, site-level variation in productivity, and inconsistancies with data collection. Any of these may be confounding on results. Some plots may have been more productive than others based on random factors independent of their pollinator networks. Additionally, there is little metadata on what a 0 means in the seed set or pollinator data, which may be limiting in the creation of a visual network. These risks can be mitigated by cleaning data and reducing the data to a smaller, specialised subset of the larger multi-year set.
