---
title: "Annotated Bibliography Final Project"
output: pdf_document
date: "2025-10-31"
bibliography: references.bib
---
```{r}
```

@bell_interspecific_2005
Two focal species, Mimulus ringens and Lobelia siphilitica, display similar flowering phenologies and floral morphologies and therefore are likely compeditors in their shared habitat of the wet meadows of central and eastern North America and share several species of pollinators. competition for pollinators between these two species was evaluated to investigate the affects of pollinator competion on reproductive success and mating systems among sympatric flowering plant species. This article conducted an experiment where arrays of homozygous marker genotypes of Mimulus were planted with Lobelia and alone and where then observed for pollinator movement and seed production. Results found that movement of pollinators between species was possitivly associated with a reduction in conspecific pollen on Mimulus resulting in a 37% reduction in mean seeds per fruit. Mimulus was also found to have signifcantly lower rates of outcrossing in arrays where Lobelia was planted leading to the conclusion that competitoon for pollinators directly incluences rates of outcrossing and in self-compatible populations with genetic load competition for pollination may reduce seed quantity and quality.

@hansen_positive_nodate
Explored small spacial scale indirect relationships mediated by direct plant-animal interactions to emphisize the significance of evaluating these relationships for basic ecological studies and applied concervation managment. This study explored the relationship of endemic palmlike Pandanus plants which are the prefered habitat of the endemic blue tailed gecko Phelsuma cepediana. This species of gecko is also a common visiting pollinator of the Malvaceae plant which grows in some habitats near patches of Pandanus. The indirect relationship between Pandanus and Malvaceae was evaluated using reproductive success as an indicator of a possitive relationship when geckos were observed as a vector for pollination. They found a possitive correlation between proximity of Pandanus patches and the reproductive success as observed by fruit sets of the Malvacea indicating a possitve trait mediated indirect interaction between two unrelated species by a pollinator of one of the species. This study emphisizes the significance of indirect relationship analysis in ecosystems that are not only preditor-prey relationships as well as inclines us to further investigate pollinator behaviors and interactions beyond visitation of plants for possitive pollination relationships. 

@johnson_competition_2022
This article is a detailed analysis of how different pollination scenarios impact plant species interactions, paralleling the community assemblage aspect of our project. They found that competition between pollinators destabilized plant interactions, reduced niche differences between plant species and disrupted potential opportunities for coexistence. Hence, the article points to pollinator decline as an increasingly problematic phenomenon, as it could threaten plant diversity and favor more common plant species as well as create unequal competitive advantages. The analysis in this article is very thourugh and the informtion on niche differences will be very helpful when understanding the underpinnings of biodiversity differences in our data. This article will thus be critical in evaluating the broader implications of our analysis, and how to interpret the results through a restoration lens. 

@moeller_pollinator_2005
This article analyses how an abundance of Clarkia specialist pollinators, is strongly affected local plant community assemblages. The research findings indicate higher abundance of specialists pollintors, yet greater biodiversity in generalist pollinators, meanwhile discussing the reproductiove success of the Clarkia as a measureable output of pollinator effectiveness. Moreover, the article notes the increased probability of generalist pollinators carrying foreign pollen within plants insdide a community, leading to less reproductive success. One limitation of this research is the absence of species spceific information on which pllinators are Clarkia speciallists. In turn, this will push us to conduct more research on which pollinator species are specialists for Clarkia or are commonly found on these flowers. This article will be very beneficial in our data analysis because it directly relates to the plants we are using seed data from. 

@ponisio_opportunistic_2017
Analyzed pollinator visitation records to better understand how communities essemble to prevent community collaps and inform how to restore lost interactions. Research sites in central california, where intensly managed agriculture utilizes monocropping, were selected for hedgrerow restoration. The sites were monitored from 2006 to 2014 before and after hedgrows were planted, for community essemply data on plant pollinator interactions. Results indicated an oppertunitistic attachement process of community assembly of plant pollinator interactions, meaning generalist species where observed continually adapting their interactions to take advantage of less competative resources as indicated by observation of significant regorganization of interactions among these restored hedgerow sites.

@ponisio_farm_2016
This article examines the impact that hedgerow maturity has on spatial heterogeneity, beta diversity and visitation in pollinator communities in intensively managed agriculture. The findings indicate that mature hedgerows promote the highest pollinator trait diversity which can create more complex and varied pollinator ecosystems. The research also suggests that hedgerows can also support more specialized and phenotypically diverse pollinator communities, where species replacement rather than loss or gain drives spatial heterogeneity. One limitation to utilising the finsings of this article, is that hedgrow maturity as an indfependent variable is very different to using different community assemblages. The research in this study was conducted over many years, and therefore enabled pollinator populatins to establish themselves nearby, unlike the short term nature of the data we are using for this project. However, the assesment of specialistion and B diversity will be very helpful, as both can be observed and measured in our project data, using the methods and formulas outlined in this study. 

@rietkerk_regular_2008
This article explores how large-scale ordered spatial patterns emerge from local plant-pollinator interactions, while focusing on the feedback mechanisms that underpin these relationships. The research found regaular spatial patterns in multiple ecosystems, where patterns emerged through long-distance negative feedback, and short distance positive feedback interactions. They suggest that self-organization in this manner is a universal ecological phenomenon and provides insight into the resilience and resource management of an ecosystem. While none of the examined ecosystems was a wetland praire (the ecosystem this project is using data from), the ecological concepts of long-distance negative feedback, and short-distance posiutive feedback, can still be applied to help our general analysis of the illustrated feedback mechanisms we find in the differnt community assemblages. The concepts on feedback at short and long distances will be important when considering the implications of the pollinator network. 

@risadsargent_role_nodate
This article created a population genetics models that uses pollinator efficiency and abundance to investigate the affects of local plant communities on floral trait specialization. The conditions for the model describe the spread of a non dominant allele which results in phenotypes which vary in degrees of pollinator attration, as well as presence of two pollinator populations within the flowers community and their affect on geneotype frequency. The predictions made using this model found that flowering species that are numerically rare compared to other animal pollinated species in the community are more likely to evolve specialist floral traits used to attract specific pollinators whereas relativly common floral species are likely to exibit generalist pollinator traits that attract many different pollinators. Results indicated that plants evolve to be pollinator specialists in communities where the species carrying a nondominant but highly attractive phenotype are rare, as a result of the increased liklyhood of random pollinator visits resulting in deposition of heterospecific pollen. This model can be used to aid in investigation of the influence of population genetics on pollinator visitation. 

@sargent_plantpollinator_2008
This article notes previous knowlege that plant neighborhoods may increase visitation levels of shared pollinators, however more understanding about fitness changes in response to pollinator identity and visitation rates in particular locations. Additionally, it introduces the concept of habitat filtering, where the environment acts as a filter, and predicts that communities that share simmilar traits result. The article explains how local pollinator community can also operate as a habitat filter if absence of a particular pollinator prevents the establishment of a plant species in a community. Thus, the findings in this article will be beneficial to helping analyse the data, where we can determine the most beneficial plant community assemblages based on the premise that plants should benefit from living in close proximity to other plants that attract the same pollinators. The article is limiting in that it does not provide an adequate way to asses or measure pollinator overlap, but instead just illustrates the research results found due to said overlap. 

@slingsby_phylogenetic_2006
Examined how phylogenetic relationships influence niche species co-existence at fine spatial scales. Found that species that co-existed were more phylogenetically distanct than expected by chance, however the pattern weekend when analyzing broader phylogenetic scales. Co-occurring species demonstrated greater functional trait divergence. They suggest that complex interactions between evolutionary history and ecological processes explain these results, indicating that closer related species can co-exist through functional differentiation.  This source will be useful to help inform a hypothesis that considers species relateness to the assembly of a pollinator network. Its anaylsis of functional trait divergence may be too detailed and irrelevent for this particular study and thus is limiting in this way, however understanding the general context of species co-exitance from a phylogenetic perspective is relevant. Ultimately, this research may help inform which species data we choose to examine from the Oregon Bee Atlas, or other relevant sources, as analysisng phylogenetically similar species may impact the success of plant communities indirectly. 





